"""Your Migration Message

Revision ID: 8b7b5c7eedd7
Revises: a50cde241c4b
Create Date: 2023-10-20 12:55:48.724146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7b5c7eedd7'
down_revision = 'a50cde241c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baked_goods', sa.Column('bakery_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_baked_goods_bakery_id_bakeries'), 'baked_goods', 'bakeries', ['bakery_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_baked_goods_bakery_id_bakeries'), 'baked_goods', type_='foreignkey')
    op.drop_column('baked_goods', 'bakery_id')
    # ### end Alembic commands ###
